name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggers

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6 # Use the latest version

    # Step 3: Configure AWS Credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Validate Terraform
    - name: Terraform Validate
      run: terraform validate

    # Step 6: Plan Terraform
    - name: Terraform Plan
      run: terraform plan

    # Step 7: Apply Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve
